# -*- coding: utf-8 -*-
"""Design.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sD7f5iKqxalkZj9prHxegfg0MNR8UFB0
"""
#import requirement 
import fastai

from fastai.vision import *
import pandas
from google.colab import files
from zipfile import ZipFile

filename="data.zip"
with ZipFile(filename,'r') as zip:
  zip.extractall()
  print("Done")

# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

#unzipped the dataset

filename="testing1.zip"
with ZipFile(filename,'r') as zip:
  zip.extractall()
  print("Done")

#train model 
Data=ImageDataBunch.from_folder("data",ds_tfms=get_transforms(),valid_pct=0.1,size=256,bs=5)

Data.normalize(imagenet_stats)

learner=create_cnn(Data,models.resnet34,metrics=accuracy)

learner.lr_find()

learner.recorder.plot()

learner.fit_one_cycle(10,1e-03)

learner.lr_find()

learner.recorder.plot()

learner.fit_one_cycle(10,1e-6)

#save module 
learner.save('Stage-1')

#enter your inpute 
img=open_image('enter image name')
#it shows the image 
img

img1=open_image('enter orther image name')
img1

img2=open_image('testing/1.jpg')
img2

#the image which you want to classify 
learner.predict(img)

